server {
    listen 80;
    server_name 192.168.1.190;

    # 托管前端静态文件
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # 反向代理后端接口
    location /api {
        proxy_pass http://blog_backend:8084/;  # 使用 Docker 容器名通信
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        rewrite ^/api/(.*) /$1 break;
        # 核心缓冲区配置（新增部分）
        client_body_buffer_size     30M;     # 内存缓冲区调至1MB，避免小文件写磁盘
#        client_body_in_single_buffer on;     # 强制请求体在单个内存缓冲区处理
        client_max_body_size        0;   # 允许上传最大1GB文件
        client_body_temp_path       /var/nginx/client_temp 1 2;  # 指定临时目录并分级存储

        # 超时控制（保持原有）
        proxy_read_timeout 600s;    # 后端响应超时
        client_body_timeout 600s;   # 客户端上传超时
    }
}



